name: GitHub Actions Demo
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: |
          npm install    

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name=publish::false
        echo ::set-output name=version::
    - name: read variables
      run: |
        CURRENT_PKG_VERSION=$(pwd)
        DEPLOYED=$([ -z "${CURRENT_PKG_VERSION}" ] && echo "UNO" || echo "VACIO")
        echo "deployed => ${DEPLOYED}"

