name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name=publish::false
        echo ::set-output name=version::
    - name: read variables
      run: |
        DEPLOYED=$([ -z "${{ steps.vars.outputs.version }}" ] && echo $(pwd) || echo ${{ steps.vars.outputs.version }})
        echo "deployed => ${DEPLOYED}"

