name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name=publish::false
        echo ::set-output name=version::
    - name: read variables
      id: read
      run: |
        DEPLOYED=$([ -z "${{ steps.vars.outputs.version }}" ] && echo "UNO" || echo "VACIO")
        echo "deployed => ${DEPLOYED}"
    - name: print variables
      run: |
        echo "deployed ${{ steps.read.outputs.deployed }}"
