name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name:publish::$("false")
        echo ::set-output name:version::$("1")
    - name: read variables
      run: |
      DEPLOYED=$([ -z "${{ steps.vars.outputs.version }}" ] && echo "UNO" || echo "VACIO")
      echo "deployed ==> ${{ $DEPLOYED }}"
